# Generated by Django 3.1.6 on 2021-02-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='meme_url',
            new_name='url',
        ),
    ]
