# Generated by Django 3.1.6 on 2021-02-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_auto_20210208_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='meme_owner',
            new_name='name',
        ),
    ]
